name: Self Test

on: [push]

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: teaminkling/autobadger@master
      - name: Pre-remote commit actions
        run: |
          git add README.md && \
            git config --local user.email "action@github.com" && \
            git config --local user.name "GitHub Action" && \
            git commit -m "[skip-ci, auto] Make changes automatically to meta files." || \
            echo "Nothing to commit."
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
